### ISSUE TITLE
numpy.ufunc size changed

### ISSUE THREAD

**Issue by edwardando** [akaszynski/pymeshfix#3]
On debian, python 2.7 and 3.5, installed with pip I get the following error:

> ----> 8 from pymeshfix import _meshfix
__init__.pxd in init pymeshfix._meshfix()

ValueError: numpy.ufunc size changed, may indicate binary incompatibility. Expected 216 from C header, got 192 from PyObject

**Comment by akaszynski** [comment]
What's your numpy version?  I just noticed on my end that if you're running ``<1.16.0`` you'll run into issues.  I'm going to rebuild it with ``1.15.0`` to make it compatible with earlier versions.

**Comment by akaszynski** [comment]
It's because I wasn't aware and didn't put it in the setup requirements.  I'm going to change that and build a new version that's less strict.  You can try upgrading numpy or waiting until I rebuild it later today.

**Comment by akaszynski** [comment]
Fixed in ``pymeshfix>=0.12.3``
